export const ARMORY_UNSORTED_SHELF_POSITION = 0;
export const ARMORY_PLAYER_SHELF_MIN_POSITION = 1;
export const ARMORY_PLAYER_SHELF_MAX_POSITION = 10;

export const ARMORY_PLAYER_SHELF_POSITIONS = Array.from(
  {
    length: ARMORY_PLAYER_SHELF_MAX_POSITION - ARMORY_PLAYER_SHELF_MIN_POSITION + 1,
  },
  (_, index) => ARMORY_PLAYER_SHELF_MIN_POSITION + index,
);
