export const PVP_CONFIGURATOR_SECTION_METADATA_NAMESPACE =
  'pvp_configurator_section';
export const PVP_RUNTIME_SECTION_METADATA_NAMESPACE = 'pvp_runtime_section';
export const PVP_TARGETING_SECTION_METADATA_NAMESPACE = 'pvp_targeting_section';
export const PVP_SPY_SECTION_METADATA_NAMESPACE = 'pvp_spy_section';
export const PVP_REWARD_SECTION_METADATA_NAMESPACE = 'pvp_reward_section';
export const PVP_RESOURCE_TRANSFER_SECTION_METADATA_NAMESPACE =
  'pvp_resource_transfer_section';
export const PVP_ANTI_ABUSE_SECTION_METADATA_NAMESPACE =
  'pvp_anti_abuse_section';
export const PVP_REPORT_SECTION_METADATA_NAMESPACE = 'pvp_report_section';

export const PVP_UI_METADATA_NAMESPACES = [
  PVP_CONFIGURATOR_SECTION_METADATA_NAMESPACE,
  PVP_RUNTIME_SECTION_METADATA_NAMESPACE,
  PVP_TARGETING_SECTION_METADATA_NAMESPACE,
  PVP_SPY_SECTION_METADATA_NAMESPACE,
  PVP_REWARD_SECTION_METADATA_NAMESPACE,
  PVP_RESOURCE_TRANSFER_SECTION_METADATA_NAMESPACE,
  PVP_ANTI_ABUSE_SECTION_METADATA_NAMESPACE,
  PVP_REPORT_SECTION_METADATA_NAMESPACE,
] as const;

export type PvpUiMetadataNamespace = typeof PVP_UI_METADATA_NAMESPACES[number];
