export const RPC = {
  has_global_role: 'has_global_role',
  assign_global_role: 'assign_global_role',
  assign_server_staff: 'assign_server_staff',
  revoke_server_staff: 'revoke_server_staff',
  can_have_moderator_scope: 'can_have_moderator_scope',
  search_server_staff_candidates: 'search_server_staff_candidates',
  set_server_staff_permission_scopes: 'set_server_staff_permission_scopes',
  user_has_hero_on_server: 'user_has_hero_on_server',
  user_has_staff_disqualifying_history: 'user_has_staff_disqualifying_history',
  create_config_change_set_draft: 'create_config_change_set_draft',
  create_config_value_change_entry: 'create_config_value_change_entry',
  get_config_definition_explainability: 'get_config_definition_explainability',
  mark_config_change_set_ready: 'mark_config_change_set_ready',
  apply_config_change_set: 'apply_config_change_set',
  cancel_config_change_set: 'cancel_config_change_set',
  write_audit_log: 'write_audit_log',
  can_manage_anti_abuse: 'can_manage_anti_abuse',
  set_anti_abuse_case_decision: 'set_anti_abuse_case_decision',
  set_player_relationship_declaration_decision:
    'set_player_relationship_declaration_decision',
  create_player_relationship_declaration: 'create_player_relationship_declaration',
  create_player_abuse_report: 'create_player_abuse_report',
  set_player_abuse_report_decision: 'set_player_abuse_report_decision',
  create_anti_abuse_sanction: 'create_anti_abuse_sanction',
  set_anti_abuse_sanction_status: 'set_anti_abuse_sanction_status',
  create_character_point_penalty_for_sanction:
    'create_character_point_penalty_for_sanction',
  set_character_point_penalty_status: 'set_character_point_penalty_status',
  add_anti_abuse_sanction_item: 'add_anti_abuse_sanction_item',
  can_apply_local_moderation_action: 'can_apply_local_moderation_action',
  can_read_full_moderation_history: 'can_read_full_moderation_history',
  can_search_moderation_targets: 'can_search_moderation_targets',
  create_moderation_action: 'create_moderation_action',
  attach_reward_drop_item_to_game_report: 'attach_reward_drop_item_to_game_report',
  create_game_report_from_combat_result: 'create_game_report_from_combat_result',
  get_full_hero_moderation_history: 'get_full_hero_moderation_history',
  get_full_user_moderation_history: 'get_full_user_moderation_history',
  get_visible_moderation_actions: 'get_visible_moderation_actions',
  search_moderation_hero_targets: 'search_moderation_hero_targets',
  search_moderation_item_targets: 'search_moderation_item_targets',
  search_moderation_user_targets: 'search_moderation_user_targets',
  create_entity_requirement: 'create_entity_requirement',
  get_ui_metadata_entries: 'get_ui_metadata_entries',
  get_start_flow_server_availability: 'get_start_flow_server_availability',
  get_account_entry_hero_contexts: 'get_account_entry_hero_contexts',
  select_account_entry_active_hero_context:
    'select_account_entry_active_hero_context',
  get_player_dashboard_page_context: 'get_player_dashboard_page_context',
  get_player_attributes_page_context: 'get_player_attributes_page_context',
  get_player_armory_page_context: 'get_player_armory_page_context',
  get_player_topbar_display_contract: 'get_player_topbar_display_contract',
  get_player_combat_common_copy: 'get_player_combat_common_copy',
  get_player_exploration_difficulty_copy: 'get_player_exploration_difficulty_copy',
  get_player_exploration_runtime_copy: 'get_player_exploration_runtime_copy',
  can_manage_game_copy: 'can_manage_game_copy',
  get_game_copy_text_entry_locales: 'get_game_copy_text_entry_locales',
  update_game_copy_text_entry: 'update_game_copy_text_entry',
  get_player_estate_page_context: 'get_player_estate_page_context',
  get_auction_page_copy: 'get_auction_page_copy',
  get_auction_page_context: 'get_auction_page_context',
  search_auction_listings_page: 'search_auction_listings_page',
  get_auction_listings_page: 'get_auction_listings_page',
  get_auction_bids_page: 'get_auction_bids_page',
  get_auction_create_context: 'get_auction_create_context',
  get_trade_page_copy: 'get_trade_page_copy',
  get_trade_page_context: 'get_trade_page_context',
  get_player_vicinity_page_context: 'get_player_vicinity_page_context',
  get_start_flow_origin_options: 'get_start_flow_origin_options',
  create_hero_start_flow: 'create_hero_start_flow',
  get_combat_turn_limit: 'get_combat_turn_limit',
  get_combat_resolution_preview: 'get_combat_resolution_preview',
  start_manual_combat_session: 'start_manual_combat_session',
  auto_resolve_combat_session: 'auto_resolve_combat_session',
  finalize_combat_source_result: 'finalize_combat_source_result',
  get_combat_live_state: 'get_combat_live_state',
  submit_combat_player_action: 'submit_combat_player_action',
  get_combat_result_detail: 'get_combat_result_detail',
  persist_combat_result_snapshot: 'persist_combat_result_snapshot',
  build_combat_opponent_equipment_loadout_snapshot:
    'build_combat_opponent_equipment_loadout_snapshot',
  build_opponent_combatant_snapshot_for_resolver:
    'build_opponent_combatant_snapshot_for_resolver',
  upsert_combat_opponent_family: 'upsert_combat_opponent_family',
  deactivate_combat_opponent_family: 'deactivate_combat_opponent_family',
  upsert_combat_opponent_definition: 'upsert_combat_opponent_definition',
  deactivate_combat_opponent_definition: 'deactivate_combat_opponent_definition',
  upsert_combat_opponent_stat_value: 'upsert_combat_opponent_stat_value',
  delete_combat_opponent_stat_value: 'delete_combat_opponent_stat_value',
  upsert_combat_opponent_attack_source: 'upsert_combat_opponent_attack_source',
  deactivate_combat_opponent_attack_source: 'deactivate_combat_opponent_attack_source',
  upsert_combat_opponent_equipment_entry: 'upsert_combat_opponent_equipment_entry',
  deactivate_combat_opponent_equipment_entry: 'deactivate_combat_opponent_equipment_entry',
  deactivate_entity_requirement: 'deactivate_entity_requirement',
  get_bonus_impact_preview: 'get_bonus_impact_preview',
  get_building_progression_preview: 'get_building_progression_preview',
  get_requirement_impact_preview: 'get_requirement_impact_preview',
  reorder_entity_requirements: 'reorder_entity_requirements',
  relocate_hero_estate_to_empty_address: 'relocate_hero_estate_to_empty_address',
  finalize_hero_estate_building_jobs: 'finalize_hero_estate_building_jobs',
  get_hero_estate_runtime_state: 'get_hero_estate_runtime_state',
  start_estate_building_upgrade: 'start_estate_building_upgrade',
  delete_game_report_for_hero: 'delete_game_report_for_hero',
  get_report_page_copy: 'get_report_page_copy',
  get_reports_center_page_context: 'get_reports_center_page_context',
  mark_all_reports_read: 'mark_all_reports_read',
  mark_reports_read: 'mark_reports_read',
  remove_reports_from_list: 'remove_reports_from_list',
  get_report_detail: 'get_report_detail',
  get_public_report_detail: 'get_public_report_detail',
  get_hero_game_report_detail: 'get_hero_game_report_detail',
  get_hero_game_report_unread_count: 'get_hero_game_report_unread_count',
  get_hero_game_reports: 'get_hero_game_reports',
  get_my_notification_unread_count: 'get_my_notification_unread_count',
  get_my_notifications: 'get_my_notifications',
  get_hero_active_runtime_activity: 'get_hero_active_runtime_activity',
  get_active_pvp_action_offer: 'get_active_pvp_action_offer',
  inspect_pvp_foundation_integration_state:
    'inspect_pvp_foundation_integration_state',
  get_hero_pvp_daily_attack_state: 'get_hero_pvp_daily_attack_state',
  get_pvp_ranking_context: 'get_pvp_ranking_context',
  get_pvp_action_copy: 'get_pvp_action_copy',
  get_pvp_combat_copy: 'get_pvp_combat_copy',
  get_pvp_report_copy: 'get_pvp_report_copy',
  get_public_pvp_report_copy: 'get_public_pvp_report_copy',
  get_pvp_ranking_copy: 'get_pvp_ranking_copy',
  get_pvp_target_candidates: 'get_pvp_target_candidates',
  get_pvp_visible_address_target_overlay:
    'get_pvp_visible_address_target_overlay',
  get_my_pvp_spy_result: 'get_my_pvp_spy_result',
  get_my_pvp_attack_result: 'get_my_pvp_attack_result',
  start_pvp_action: 'start_pvp_action',
  settle_due_pvp_spy_action: 'settle_due_pvp_spy_action',
  skip_active_pvp_attack_travel_timer:
    'skip_active_pvp_attack_travel_timer',
  create_pvp_spy_game_report: 'create_pvp_spy_game_report',
  get_my_staff_notification_unread_count: 'get_my_staff_notification_unread_count',
  get_my_staff_notifications: 'get_my_staff_notifications',
  get_admin_notification_db_owned_producer_diagnostics:
    'get_admin_notification_db_owned_producer_diagnostics',
  get_public_game_report_by_token: 'get_public_game_report_by_token',
  dismiss_notification: 'dismiss_notification',
  mark_notification_read: 'mark_notification_read',
  mark_game_report_read: 'mark_game_report_read',
  get_vendor_scrap_drachma_payout_percent:
    'get_vendor_scrap_drachma_payout_percent',
  item_popover_copy: 'item_popover_copy',
  item_popover_detail: 'item_popover_detail',
  get_hero_item_requirement_status: 'get_hero_item_requirement_status',
  get_item_effective_requirements: 'get_item_effective_requirements',
  get_item_requirement_component_rows: 'get_item_requirement_component_rows',
  check_hero_meets_item_requirements: 'check_hero_meets_item_requirements',
  rename_hero_armory_shelf: 'rename_hero_armory_shelf',
  move_hero_armory_item_to_shelf: 'move_hero_armory_item_to_shelf',
  bulk_move_hero_armory_items_to_shelf:
    'bulk_move_hero_armory_items_to_shelf',
  get_hero_equipment_runtime_slots: 'get_hero_equipment_runtime_slots',
  get_hero_equipment_runtime_bonus_rows: 'get_hero_equipment_runtime_bonus_rows',
  get_hero_equipment_runtime_bonus_totals:
    'get_hero_equipment_runtime_bonus_totals',
  get_hero_dashboard_runtime_stats: 'get_hero_dashboard_runtime_stats',
  get_hero_attribute_allocation_preview_manifest:
    'get_hero_attribute_allocation_preview_manifest',
  get_hero_health_state: 'get_hero_health_state',
  cancel_guild_join_request: 'cancel_guild_join_request',
  demote_guild_officer: 'demote_guild_officer',
  get_guild_config_summary: 'get_guild_config_summary',
  cancel_guild_invite: 'cancel_guild_invite',
  create_guild: 'create_guild',
  create_guild_invite: 'create_guild_invite',
  create_guild_join_request: 'create_guild_join_request',
  get_hero_guild_dashboard: 'get_hero_guild_dashboard',
  get_hero_guild_emergency_election_candidate_rows:
    'get_hero_guild_emergency_election_candidate_rows',
  get_hero_guild_emergency_election_summary:
    'get_hero_guild_emergency_election_summary',
  get_hero_guild_armory_item_rows: 'get_hero_guild_armory_item_rows',
  get_hero_guild_armory_loan_rows: 'get_hero_guild_armory_loan_rows',
  get_hero_guild_invitation_rows: 'get_hero_guild_invitation_rows',
  get_hero_guild_join_request_rows: 'get_hero_guild_join_request_rows',
  get_hero_guild_members: 'get_hero_guild_members',
  get_hero_guild_state: 'get_hero_guild_state',
  borrow_guild_armory_item: 'borrow_guild_armory_item',
  deposit_guild_armory_item: 'deposit_guild_armory_item',
  disband_guild: 'disband_guild',
  finalize_guild_emergency_election: 'finalize_guild_emergency_election',
  force_return_guild_armory_loan: 'force_return_guild_armory_loan',
  kick_guild_member: 'kick_guild_member',
  leave_guild: 'leave_guild',
  nominate_guild_emergency_leader_candidate:
    'nominate_guild_emergency_leader_candidate',
  promote_guild_member_to_officer: 'promote_guild_member_to_officer',
  remove_guild_armory_item: 'remove_guild_armory_item',
  respond_guild_invite: 'respond_guild_invite',
  return_guild_armory_loan: 'return_guild_armory_loan',
  review_guild_join_request: 'review_guild_join_request',
  search_guilds_for_hero: 'search_guilds_for_hero',
  set_guild_armory_member_access: 'set_guild_armory_member_access',
  start_guild_emergency_election: 'start_guild_emergency_election',
  start_guild_emergency_election_voting:
    'start_guild_emergency_election_voting',
  vote_guild_emergency_election: 'vote_guild_emergency_election',
  withdraw_guild_armory_item: 'withdraw_guild_armory_item',
  equip_hero_item: 'equip_hero_item',
  unequip_hero_item: 'unequip_hero_item',
  bulk_unequip_hero_items: 'bulk_unequip_hero_items',
  bulk_equip_hero_items: 'bulk_equip_hero_items',
  bulk_vendor_scrap_hero_items: 'bulk_vendor_scrap_hero_items',
  get_hero_loadout_presets: 'get_hero_loadout_presets',
  rename_hero_loadout_preset: 'rename_hero_loadout_preset',
  save_current_hero_loadout_preset: 'save_current_hero_loadout_preset',
  clear_hero_loadout_preset: 'clear_hero_loadout_preset',
  preview_hero_loadout_preset: 'preview_hero_loadout_preset',
  apply_hero_loadout_preset: 'apply_hero_loadout_preset',
  recover_scrapped_item: 'recover_scrapped_item',
  add_hero_remaining_actions: 'add_hero_remaining_actions',
  auto_resolve_hero_exploration_challenge_attempt:
    'auto_resolve_hero_exploration_challenge_attempt',
  complete_hero_exploration_challenge_attempt:
    'complete_hero_exploration_challenge_attempt',
  force_complete_hero_exploration_challenge_attempt:
    'force_complete_hero_exploration_challenge_attempt',
  get_hero_exploration_debug_state: 'get_hero_exploration_debug_state',
  reset_hero_exploration: 'reset_hero_exploration',
  resolve_hero_exploration_step: 'resolve_hero_exploration_step',
  set_next_hero_exploration_outcome_override:
    'set_next_hero_exploration_outcome_override',
  skip_hero_exploration_step_timer: 'skip_hero_exploration_step_timer',
  search_recoverable_scrapped_items_page: 'search_recoverable_scrapped_items_page',
  test_grant_reward_profile_to_hero: 'test_grant_reward_profile_to_hero',
  vendor_scrap_hero_item: 'vendor_scrap_hero_item',
  create_player_direct_trade_offer: 'create_player_direct_trade_offer',
  respond_player_direct_trade_offer: 'respond_player_direct_trade_offer',
  confirm_player_direct_trade_offer: 'confirm_player_direct_trade_offer',
  cancel_player_direct_trade_offer: 'cancel_player_direct_trade_offer',
  reject_player_direct_trade_offer: 'reject_player_direct_trade_offer',
  create_player_auction_listing: 'create_player_auction_listing',
  place_player_auction_bid: 'place_player_auction_bid',
  buy_now_player_auction: 'buy_now_player_auction',
  close_player_auction_listing: 'close_player_auction_listing',
  cancel_player_auction_listing: 'cancel_player_auction_listing',
  get_exploration_challenge_reward_read_model:
    'get_exploration_challenge_reward_read_model',
  get_exploration_step_reward_read_model:
    'get_exploration_step_reward_read_model',
  get_exploration_step_duration_seconds: 'get_exploration_step_duration_seconds',
  get_hero_exploration_difficulty_card_previews:
    'get_hero_exploration_difficulty_card_previews',
  get_hero_exploration_state: 'get_hero_exploration_state',
  get_hero_pending_combat_effect_state: 'get_hero_pending_combat_effect_state',
  get_encounter_definition_readiness: 'get_encounter_definition_readiness',
  get_trial_definition_readiness: 'get_trial_definition_readiness',
  preview_challenge_auto_resolve_success_chance:
    'preview_challenge_auto_resolve_success_chance',
  preview_combat_luck_formula_context: 'preview_combat_luck_formula_context',
  preview_exploration_luck_rng_chain: 'preview_exploration_luck_rng_chain',
  preview_non_trial_encounter_chance: 'preview_non_trial_encounter_chance',
  preview_reward_generated_item: 'preview_reward_generated_item',
  preview_reward_generated_item_distribution_luck:
    'preview_reward_generated_item_distribution_luck',
  preview_reward_generated_item_luck: 'preview_reward_generated_item_luck',
  preview_reward_profile: 'preview_reward_profile',
  preview_reward_profile_luck: 'preview_reward_profile_luck',
  preview_trial_manifestation_chance: 'preview_trial_manifestation_chance',
  preview_trial_opportunity_curve: 'preview_trial_opportunity_curve',
  simulate_trial_opportunity_runs: 'simulate_trial_opportunity_runs',
  start_hero_exploration_step: 'start_hero_exploration_step',
  start_or_get_hero_exploration: 'start_or_get_hero_exploration',
  start_or_get_hero_exploration_and_start_initial_step:
    'start_or_get_hero_exploration_and_start_initial_step',
  upsert_trial_definition: 'upsert_trial_definition',
  upsert_trial_combat_candidate: 'upsert_trial_combat_candidate',
  deactivate_trial_combat_candidate: 'deactivate_trial_combat_candidate',
  upsert_encounter_definition: 'upsert_encounter_definition',
  deactivate_encounter_definition: 'deactivate_encounter_definition',
  upsert_encounter_combat_candidate: 'upsert_encounter_combat_candidate',
  deactivate_encounter_combat_candidate: 'deactivate_encounter_combat_candidate',
  upsert_encounter_resource_payload: 'upsert_encounter_resource_payload',
  deactivate_encounter_resource_payload: 'deactivate_encounter_resource_payload',
  upsert_encounter_effect_payload: 'upsert_encounter_effect_payload',
  deactivate_encounter_effect_payload: 'deactivate_encounter_effect_payload',
  upsert_exploration_effect_definition: 'upsert_exploration_effect_definition',
  deactivate_exploration_effect_definition: 'deactivate_exploration_effect_definition',
  upsert_reward_outcome_kind: 'upsert_reward_outcome_kind',
  deactivate_reward_outcome_kind: 'deactivate_reward_outcome_kind',
  upsert_reward_profile: 'upsert_reward_profile',
  deactivate_reward_profile: 'deactivate_reward_profile',
  upsert_reward_profile_entry: 'upsert_reward_profile_entry',
  deactivate_reward_profile_entry: 'deactivate_reward_profile_entry',
  upsert_reward_profile_assignment: 'upsert_reward_profile_assignment',
  deactivate_reward_profile_assignment: 'deactivate_reward_profile_assignment',
  get_hero_experience_to_next_level: 'get_hero_experience_to_next_level',
  get_hero_prestige_public_summary: 'get_hero_prestige_public_summary',
  get_hero_trial_power: 'get_hero_trial_power',
  get_luck_lab_preview_contracts: 'get_luck_lab_preview_contracts',
  grant_hero_experience: 'grant_hero_experience',
  preview_luck_influence_and_trial_power: 'preview_luck_influence_and_trial_power',
  save_stat_allocation: 'save_stat_allocation',
  update_entity_requirement: 'update_entity_requirement',
} as const;
