export const RPC = {
  has_global_role: 'has_global_role',
  assign_global_role: 'assign_global_role',
  assign_server_staff: 'assign_server_staff',
  revoke_server_staff: 'revoke_server_staff',
  can_have_moderator_scope: 'can_have_moderator_scope',
  search_server_staff_candidates: 'search_server_staff_candidates',
  set_server_staff_permission_scopes: 'set_server_staff_permission_scopes',
  user_has_hero_on_server: 'user_has_hero_on_server',
  user_has_staff_disqualifying_history: 'user_has_staff_disqualifying_history',
  create_config_change_set_draft: 'create_config_change_set_draft',
  create_config_value_change_entry: 'create_config_value_change_entry',
  get_config_definition_explainability: 'get_config_definition_explainability',
  mark_config_change_set_ready: 'mark_config_change_set_ready',
  apply_config_change_set: 'apply_config_change_set',
  cancel_config_change_set: 'cancel_config_change_set',
  write_audit_log: 'write_audit_log',
  can_manage_anti_abuse: 'can_manage_anti_abuse',
  set_anti_abuse_case_decision: 'set_anti_abuse_case_decision',
  set_player_relationship_declaration_decision:
    'set_player_relationship_declaration_decision',
  create_player_relationship_declaration: 'create_player_relationship_declaration',
  create_player_abuse_report: 'create_player_abuse_report',
  set_player_abuse_report_decision: 'set_player_abuse_report_decision',
  create_anti_abuse_sanction: 'create_anti_abuse_sanction',
  set_anti_abuse_sanction_status: 'set_anti_abuse_sanction_status',
  create_character_point_penalty_for_sanction:
    'create_character_point_penalty_for_sanction',
  set_character_point_penalty_status: 'set_character_point_penalty_status',
  add_anti_abuse_sanction_item: 'add_anti_abuse_sanction_item',
  can_apply_local_moderation_action: 'can_apply_local_moderation_action',
  can_read_full_moderation_history: 'can_read_full_moderation_history',
  can_search_moderation_targets: 'can_search_moderation_targets',
  create_moderation_action: 'create_moderation_action',
  get_full_hero_moderation_history: 'get_full_hero_moderation_history',
  get_full_user_moderation_history: 'get_full_user_moderation_history',
  get_visible_moderation_actions: 'get_visible_moderation_actions',
  search_moderation_hero_targets: 'search_moderation_hero_targets',
  search_moderation_item_targets: 'search_moderation_item_targets',
  search_moderation_user_targets: 'search_moderation_user_targets',
  create_entity_requirement: 'create_entity_requirement',
  deactivate_entity_requirement: 'deactivate_entity_requirement',
  get_bonus_impact_preview: 'get_bonus_impact_preview',
  get_building_progression_preview: 'get_building_progression_preview',
  get_requirement_impact_preview: 'get_requirement_impact_preview',
  reorder_entity_requirements: 'reorder_entity_requirements',
  get_vendor_scrap_drachma_payout_percent:
    'get_vendor_scrap_drachma_payout_percent',
  recover_scrapped_item: 'recover_scrapped_item',
  add_hero_remaining_actions: 'add_hero_remaining_actions',
  auto_resolve_hero_exploration_challenge_attempt:
    'auto_resolve_hero_exploration_challenge_attempt',
  complete_hero_exploration_challenge_attempt:
    'complete_hero_exploration_challenge_attempt',
  force_complete_hero_exploration_challenge_attempt:
    'force_complete_hero_exploration_challenge_attempt',
  get_hero_exploration_debug_state: 'get_hero_exploration_debug_state',
  reset_hero_exploration: 'reset_hero_exploration',
  resolve_hero_exploration_step: 'resolve_hero_exploration_step',
  set_next_hero_exploration_outcome_override:
    'set_next_hero_exploration_outcome_override',
  skip_hero_exploration_step_timer: 'skip_hero_exploration_step_timer',
  scrap_hero_item: 'scrap_hero_item',
  search_recoverable_scrapped_items_page: 'search_recoverable_scrapped_items_page',
  test_grant_reward_profile_to_hero: 'test_grant_reward_profile_to_hero',
  vendor_scrap_hero_item: 'vendor_scrap_hero_item',
  create_player_direct_trade_offer: 'create_player_direct_trade_offer',
  respond_player_direct_trade_offer: 'respond_player_direct_trade_offer',
  confirm_player_direct_trade_offer: 'confirm_player_direct_trade_offer',
  cancel_player_direct_trade_offer: 'cancel_player_direct_trade_offer',
  reject_player_direct_trade_offer: 'reject_player_direct_trade_offer',
  create_player_auction_listing: 'create_player_auction_listing',
  place_player_auction_bid: 'place_player_auction_bid',
  buy_now_player_auction: 'buy_now_player_auction',
  close_player_auction_listing: 'close_player_auction_listing',
  cancel_player_auction_listing: 'cancel_player_auction_listing',
  get_hero_exploration_state: 'get_hero_exploration_state',
  preview_challenge_auto_resolve_success_chance:
    'preview_challenge_auto_resolve_success_chance',
  preview_reward_generated_item: 'preview_reward_generated_item',
  preview_reward_profile: 'preview_reward_profile',
  preview_trial_manifestation_chance: 'preview_trial_manifestation_chance',
  preview_trial_opportunity_curve: 'preview_trial_opportunity_curve',
  simulate_trial_opportunity_runs: 'simulate_trial_opportunity_runs',
  start_hero_exploration_step: 'start_hero_exploration_step',
  start_or_get_hero_exploration: 'start_or_get_hero_exploration',
  upsert_trial_definition: 'upsert_trial_definition',
  upsert_trial_combat_candidate: 'upsert_trial_combat_candidate',
  deactivate_trial_combat_candidate: 'deactivate_trial_combat_candidate',
  save_stat_allocation: 'save_stat_allocation',
  update_entity_requirement: 'update_entity_requirement',
} as const;
