export const TABLES = {
  stats: 'stats',
  items: 'items',
  monsters: 'monsters',
  heroes: 'heroes',
  user_data: 'user_data',
  bonus_templates: 'bonus_templates',
  bonus_targets: 'bonus_targets',
  buildings: 'buildings',
  building_bonuses: 'building_bonuses',
  building_requirements: 'building_requirements',
  building_resource_costs: 'building_resource_costs',
  estate_buildings: 'estate_buildings',
  estate_districts: 'estate_districts',
  hero: 'hero',
  estates: 'estates',
  hero_stats: 'hero_stats',
  hero_resources: 'hero_resources',
  hero_derived: 'hero_derived',
  entity_formula_assignments: 'entity_formula_assignments',
  game_servers: 'game_servers',
  roles: 'roles',
  server_memberships: 'server_memberships',
  server_staff_assignments: 'server_staff_assignments',
} as const;
