import { PvpActionCopy } from '../domain/pvp/pvp-action-copy.model';

const key = (path: string): string => `pvpActionCopy.${path}`;

export function pvpActionCopyKeyFallback(): PvpActionCopy {
  return {
    contractKey: 'pvp_action_copy',
    contractVersion: 'pvp_action_copy_v1',
    requestedLocale: 'pl',
    locale: 'pl',
    fallbackLocale: 'en',
    common: {
      labels: {
        combat: key('common.labels.combat'),
        heroCombat: key('common.labels.heroCombat'),
        attack: key('common.labels.attack'),
        attackAction: key('common.labels.attackAction'),
        spyAction: key('common.labels.spyAction'),
        spyProgress: key('common.labels.spyProgress'),
        scouting: key('common.labels.scouting'),
        siege: key('common.labels.siege'),
        report: key('common.labels.report'),
        combatReport: key('common.labels.combatReport'),
        spyReport: key('common.labels.spyReport'),
        target: key('common.labels.target'),
        action: key('common.labels.action'),
        state: key('common.labels.state'),
        address: key('common.labels.address'),
        targetAddress: key('common.labels.targetAddress'),
        yourAddress: key('common.labels.yourAddress'),
        protection: key('common.labels.protection'),
        actions: key('common.labels.actions'),
        guild: key('common.labels.guild'),
        level: key('common.labels.level'),
        rankPosition: key('common.labels.rankPosition'),
        remainingTime: key('common.labels.remainingTime'),
        arrivalTime: key('common.labels.arrivalTime'),
        availableFrom: key('common.labels.availableFrom'),
        decisionTime: key('common.labels.decisionTime'),
        combatLog: key('common.labels.combatLog'),
        result: key('common.labels.result'),
        battleLoot: key('common.labels.battleLoot'),
        resources: key('common.labels.resources'),
        experience: key('common.labels.experience'),
        glory: key('common.labels.glory'),
        rank: key('common.labels.rank'),
        buildings: key('common.labels.buildings'),
        equipment: key('common.labels.equipment'),
        stats: key('common.labels.stats'),
        detection: key('common.labels.detection'),
      },
      richText: {
        gloryLabel: {
          text: key('common.richText.gloryLabel.text'),
          tone: 'heading',
        },
      },
      emptyValues: {
        noData: key('common.emptyValues.noData'),
        noTarget: key('common.emptyValues.noTarget'),
        noGuild: key('common.emptyValues.noGuild'),
        noAttackProtection: key('common.emptyValues.noAttackProtection'),
        noValue: key('common.emptyValues.noValue'),
      },
      actionLabels: {
        refresh: key('common.actionLabels.refresh'),
        openReport: key('common.actionLabels.openReport'),
        resolveManual: key('common.actionLabels.resolveManual'),
        resolveAuto: key('common.actionLabels.resolveAuto'),
        enterCombat: key('common.actionLabels.enterCombat'),
        backToVicinity: key('common.actionLabels.backToVicinity'),
        attack: key('common.actionLabels.attack'),
        spy: key('common.actionLabels.spy'),
        siege: key('common.actionLabels.siege'),
      },
      actionTooltips: {
        attack: key('common.actionTooltips.attack'),
        spy: key('common.actionTooltips.spy'),
        siegeUnavailable: key('common.actionTooltips.siegeUnavailable'),
        resolveManual: key('common.actionTooltips.resolveManual'),
        resolveAuto: key('common.actionTooltips.resolveAuto'),
        openReport: key('common.actionTooltips.openReport'),
        refresh: key('common.actionTooltips.refresh'),
      },
    },
    activeAction: {
      panel: {
        defaultTitle: key('activeAction.panel.defaultTitle'),
        attackTitle: key('activeAction.panel.attackTitle'),
        spyTitle: key('activeAction.panel.spyTitle'),
        returnTitle: key('activeAction.panel.returnTitle'),
        attackAriaLabel: key('activeAction.panel.attackAriaLabel'),
        spyAriaLabel: key('activeAction.panel.spyAriaLabel'),
        returnAriaLabel: key('activeAction.panel.returnAriaLabel'),
      },
      time: {
        remainingTimeLabel: key('activeAction.time.remainingTimeLabel'),
        attackTravelLabel: key('activeAction.time.attackTravelLabel'),
        spyTravelLabel: key('activeAction.time.spyTravelLabel'),
        returnTravelLabel: key('activeAction.time.returnTravelLabel'),
        decisionWindowLabel: key('activeAction.time.decisionWindowLabel'),
      },
      phaseText: {
        attackTravel: key('activeAction.phaseText.attackTravel'),
        spyTravel: key('activeAction.phaseText.spyTravel'),
        attackManualWindow: key('activeAction.phaseText.attackManualWindow'),
        attackReturn: key('activeAction.phaseText.attackReturn'),
        attackResolved: key('activeAction.phaseText.attackResolved'),
        spyResolved: key('activeAction.phaseText.spyResolved'),
      },
      loading: {
        refreshSpyState: key('activeAction.loading.refreshSpyState'),
        refreshAttackState: key('activeAction.loading.refreshAttackState'),
        refreshDecisionState: key('activeAction.loading.refreshDecisionState'),
        refreshReturnState: key('activeAction.loading.refreshReturnState'),
        refreshUnknownState: key('activeAction.loading.refreshUnknownState'),
      },
      readyStates: {
        decisionReady: key('activeAction.readyStates.decisionReady'),
        targetReached: key('activeAction.readyStates.targetReached'),
        heroReturned: key('activeAction.readyStates.heroReturned'),
        reportReady: key('activeAction.readyStates.reportReady'),
      },
    },
    combatHandoff: {
      header: {
        eyebrowCommonKey: 'common.labels.combat',
        titleCommonKey: 'common.labels.heroCombat',
        description: key('combatHandoff.header.description'),
      },
      decisionWindow: {
        eyebrow: key('combatHandoff.decisionWindow.eyebrow'),
        title: key('combatHandoff.decisionWindow.title'),
        description: key('combatHandoff.decisionWindow.description'),
        decisionWindowLabelCommonKey: 'common.labels.decisionTime',
        manualActionCommonKey: 'common.actionLabels.resolveManual',
        autoActionCommonKey: 'common.actionLabels.resolveAuto',
        waitingForDecision: key('combatHandoff.decisionWindow.waitingForDecision'),
      },
      emptyCombatLog: {
        titleCommonKey: 'common.labels.combatLog',
        text: key('combatHandoff.emptyCombatLog.text'),
      },
    },
    eligibility: {
      statusLabels: {
        available: key('eligibility.statusLabels.available'),
        unavailable: key('eligibility.statusLabels.unavailable'),
        actionUnavailable: key('eligibility.statusLabels.actionUnavailable'),
      },
      disabledReasonTooltips: {
        targetProtected: key('eligibility.disabledReasonTooltips.targetProtected'),
        attackerBusy: key('eligibility.disabledReasonTooltips.attackerBusy'),
        targetLevelTooHigh: key('eligibility.disabledReasonTooltips.targetLevelTooHigh'),
        targetLevelTooLow: key('eligibility.disabledReasonTooltips.targetLevelTooLow'),
        sameGuild: key('eligibility.disabledReasonTooltips.sameGuild'),
        actionUnavailable: key('eligibility.disabledReasonTooltips.actionUnavailable'),
        dailyAttackLimitReached: key('eligibility.disabledReasonTooltips.dailyAttackLimitReached'),
        cooldownActive: key('eligibility.disabledReasonTooltips.cooldownActive'),
        siegeNotAvailable: key('eligibility.disabledReasonTooltips.siegeNotAvailable'),
      },
    },
  };
}
